In [1]:
# Import required libraries
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
import pandas as pd 
import numpy as np

In [2]:
# Load the data
titanic = pd.read_csv('titanic_train.csv')
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
titanic.rename(columns={'Survived': 'class'}, inplace=True)

In [4]:
for cat in ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']:
    print("Number of levels in category '{0}': \b {1:2.2f} ".format(cat, titanic[cat].unique().size))

Number of levels in category 'Name':  891.00 
Number of levels in category 'Sex':  2.00 
Number of levels in category 'Ticket':  681.00 
Number of levels in category 'Cabin':  148.00 
Number of levels in category 'Embarked':  4.00 


In [6]:
titanic['Sex'] = titanic['Sex'].map({'male':0,'female':1})
titanic['Embarked'] = titanic['Embarked'].map({'S':0,'C':1,'Q':2})
titanic

PassengerId  class  Pclass  \
0              1      0       3   
1              2      1       1   
2              3      1       3   
3              4      1       1   
4              5      0       3   
5              6      0       3   
6              7      0       1   
7              8      0       3   
8              9      1       3   
9             10      1       2   
10            11      1       3   
11            12      1       1   
12            13      0       3   
13            14      0       3   
14            15      0       3   
15            16      1       2   
16            17      0       3   
17            18      1       2   
18            19      0       3   
19            20      1       3   
20            21      0       2   
21            22      1       2   
22            23      1       3   
23            24      1       1   
24            25      0       3   
25            26      1       3   
26            27      0       3   
27            28      0       1   
28            29      1       3   
29            30      0       3   
..           ...    ...     ...   
861          862      0       2   
862          863      1       1   
863          864      0       3   
864          865      0       2   
865          866      1       2   
866          867      1       2   
867          868      0       1   
868          869      0       3   
869          870      1       3   
870          871      0       3   
871          872      1       1   
872          873      0       1   
873          874      0       3   
874          875      1       2   
875          876      1       3   
876          877      0       3   
877          878      0       3   
878          879      0       3   
879          880      1       1   
880          881      1       2   
881          882      0       3   
882          883      0       3   
883          884      0       2   
884          885      0       3   
885          886      0       3   
886          887      0       2   
887          888      1       1   
888          889      0       3   
889          890      1       1   
890          891      0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris  NaN  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  NaN  38.0      1   
2                               Heikkinen, Miss. Laina  NaN  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  NaN  35.0      1   
4                             Allen, Mr. William Henry  NaN  35.0      0   
5                                     Moran, Mr. James  NaN   NaN      0   
6                              McCarthy, Mr. Timothy J  NaN  54.0      0   
7                       Palsson, Master. Gosta Leonard  NaN   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  NaN  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  NaN  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  NaN   4.0      1   
11                            Bonnell, Miss. Elizabeth  NaN  58.0      0   
12                      Saundercock, Mr. William Henry  NaN  20.0      0   
13                         Andersson, Mr. Anders Johan  NaN  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  NaN  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   NaN  55.0      0   
16                                Rice, Master. Eugene  NaN   2.0      4   
17                        Williams, Mr. Charles Eugene  NaN   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  NaN  31.0      1   
19                             Masselmani, Mrs. Fatima  NaN   NaN      0   
20                                Fynney, Mr. Joseph J  NaN  35.0      0   
21                               Beesley, Mr. Lawrence  NaN  34.0      0   
22                         McGowan, Miss. Anna "Annie"  NaN  15.0      0   
23        

In [7]:
titanic = titanic.fillna(-999)
pd.isnull(titanic).any()

PassengerId    False
class          False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

In [8]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
CabinTrans = mlb.fit_transform([{str(val)} for val in titanic['Cabin'].values])

In [9]:
CabinTrans

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ..., 
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [10]:
titanic_new = titanic.drop(['Name','Ticket','Cabin','class'], axis=1)

In [11]:
assert (len(titanic['Cabin'].unique()) == len(mlb.classes_)), "Not Equal" #check correct encoding done

In [12]:
titanic_new = np.hstack((titanic_new.values,CabinTrans))

In [13]:
titanic_new

array([[   1.,    3., -999., ...,    0.,    0.,    0.],
       [   2.,    1., -999., ...,    0.,    0.,    0.],
       [   3.,    3., -999., ...,    0.,    0.,    0.],
       ..., 
       [ 889.,    3., -999., ...,    0.,    0.,    0.],
       [ 890.,    1., -999., ...,    0.,    0.,    0.],
       [ 891.,    3., -999., ...,    0.,    0.,    0.]])

In [14]:
np.isnan(titanic_new).any()

False

In [15]:
titanic_new[0].size

156

In [16]:
titanic_class = titanic['class'].values

In [17]:
training_indices, validation_indices = training_indices, testing_indices = train_test_split(titanic.index, stratify = titanic_class, train_size=0.75, test_size=0.25)
training_indices.size, validation_indices.size

(668, 223)

In [18]:
tpot = TPOTClassifier(verbosity=2, max_time_mins=2, max_eval_time_mins=0.04, population_size=40)
tpot.fit(titanic_new[training_indices], titanic_class[training_indices])

/opt/conda/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Optimization Progress: 87pipeline [00:49,  1.19pipeline/s]

Generation 1 - Current best internal CV score: 0.7185550110766137


Optimization Progress: 131pipeline [01:13,  1.83pipeline/s]

Generation 2 - Current best internal CV score: 0.7185550110766137


Optimization Progress: 175pipeline [01:53,  1.39s/pipeline]

Generation 3 - Current best internal CV score: 0.7185550110766137



2.031954183333333 minutes have elapsed. TPOT will close down.
TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: XGBClassifier(MaxAbsScaler(input_matrix), learning_rate=0.1, max_depth=8, min_child_weight=20, n_estimators=100, nthread=1, subsample=0.65)


TPOTClassifier(config_dict={'sklearn.preprocessing.MaxAbsScaler': {}, 'sklearn.preprocessing.StandardScaler': {}, 'sklearn.feature_selection.RFE': {'step': array([ 0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,
        0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,
        0.95,  1.  ...ighborsClassifier': {'n_neighbors': range(1, 101), 'weights': ['uniform', 'distance'], 'p': [1, 2]}},
        crossover_rate=0.1, cv=5, disable_update_check=False,
        early_stop=None, generations=1000000, max_eval_time_mins=0.04,
        max_time_mins=2, memory=None, mutation_rate=0.9, n_jobs=1,
        offspring_size=40, periodic_checkpoint_folder=None,
        population_size=40, random_state=None, scoring=None, subsample=1.0,
        verbosity=2, warm_start=False)

In [19]:
tpot.score(titanic_new[validation_indices], titanic.loc[validation_indices, 'class'].values)

0.73991031390134532

In [20]:
tpot.export('tpot_titanic_pipeline.py')

True

In [23]:
titanic_sub = pd.read_csv('titanic_test.csv')
titanic_sub.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [24]:
for var in ['Cabin']: #,'Name','Ticket']:
    new = list(set(titanic_sub[var]) - set(titanic[var]))
    titanic_sub.ix[titanic_sub[var].isin(new), var] = -999

/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  app.launch_new_instance()


In [25]:
titanic_sub['Sex'] = titanic_sub['Sex'].map({'male':0,'female':1})
titanic_sub['Embarked'] = titanic_sub['Embarked'].map({'S':0,'C':1,'Q':2})

In [27]:
titanic_sub = titanic_sub.fillna(-999)
pd.isnull(titanic_sub).any()

PassengerId    False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

In [28]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
SubCabinTrans = mlb.fit([{str(val)} for val in titanic['Cabin'].values]).transform([{str(val)} for val in titanic_sub['Cabin'].values])
titanic_sub = titanic_sub.drop(['Name','Ticket','Cabin'], axis=1)

In [29]:
titanic_sub_new = np.hstack((titanic_sub.values,SubCabinTrans))

In [30]:
np.any(np.isnan(titanic_sub_new))

False

In [31]:
assert (titanic_new.shape[1] == titanic_sub_new.shape[1]), "Not Equal"

In [32]:
submission = tpot.predict(titanic_sub_new)

In [36]:
submission

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0,

In [38]:
final = pd.DataFrame({'PassengerId': titanic_sub['PassengerId'], 'Survived': submission})
final.to_csv('submissioneee.csv', index = False)

In [39]:
final.shape

(418, 2)